### PR TITLE
#6 - Add docker support

### PR DESCRIPTION
**Pull request by bjtulinl**
- Add Dockerfile and requirements

### CODE REVIEW

**Comment by jcklie** [comment]
@bjtulinl Can you add a README for how to build the docker and how to use it?

**Review by jcklie — APPROVED** [review]
Works for me. Some minor things:
- the `--it` did not work for me, it says it does not know that parameter
- You do not need a docker account for building docker images

**Comment by bjtulinl** [comment]
My bad. It should be "-it" instead of "--it". But a docker account is needed when you start the Docker Desktop, right?

**Comment by jcklie** [comment]
> My bad. It should be "-it" instead of "--it". But a docker account is needed when you start the Docker Desktop, right?

For docker on Ubuntu, you do not need an account

**Comment by bjtulinl** [comment]
> > My bad. It should be "-it" instead of "--it". But a docker account is needed when you start the Docker Desktop, right?
> 
> For docker on Ubuntu, you do not need an account

Ok. I will modify this part.

**Pull request merged**
